### ISSUE TITLE
Cannot Run Preprocess Standard Scalar

### ISSUE THREAD

**Issue by ryan11lee** [emmettgb/Lathe.jl#40]
![image](https://user-images.githubusercontent.com/45303876/87253482-64fd0800-c430-11ea-9ecd-ccecbe796bc2.png)

When I run the function I get the attached error.

**Comment by emmettgb** [comment]
Hi Ryan, you are getting this error because you **cannot** use StandardScalar on a DataFrame. Instead use it on an Array, or DataFrame column. Let's say your column is called "X":
```julia
xtrain = df[:X]
scaled_xtrain = StandardScalar(xtrain)

**Comment by ryan11lee** [comment]
Thanks for the quick response. Out of curiosity if I wanted to look at the values that were scaled, what is the best way to move the prediction into a DataFrame (i did in the code below) and concatenate for each column.


I tried 
```
append!(new_df, scaled_feature)
```
Here is the code I got do most of what I needed for right now

```
for col in names(X)
    println(col)
    feeder = X[!, col]
    scaled_feature = (StandardScalar(feeder))
    scaled_feature = scaled_feature.predict(feeder) |>
    DataFrame
    scaled_feature = select(scaled_feature, :re => col, :im => :DROP) |> # rename columns
    @select(-:DROP) |>
    DataFrame
    println("mean:")
    mean = Lathe.stats.mean(scaled_feature[!, col])
    println(mean)
    println("STD:")
    std = Lathe.stats.std(scaled_feature[!, col])
    println(std)
end
```

**Comment by emmettgb** [comment]
You could always simply set it equal to the scaled version of itself. If I wanted to scale a full DataFrame, I would do it something like this:
```julia
for col in df
    df[!, col] = StandardScalar(df[!, col]
end
```
Alternatively, in order to concatenate you could use the various Join methods provided by DataFrames.jl. Here is a link to the documentation on using such methods:
https://juliadata.github.io/DataFrames.jl/stable/man/joins/
There is probably a way you could do it with push!() or something similar from base as well.
Last but not least, I made a little notebook that might help to get you on the right track with using the normalizer.
https://github.com/emmettgb/Emmetts-DS-NoteBooks/blob/master/Julia/DFStandardScalar.ipynb

**Comment by ryan11lee** [comment]
Thank again for all the help. It really got me into using more of Lathe. Such a great package!
